news/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', NewsList.as_view(), name='News_list'),
    path('<int:pk>', Textnews.as_view(), name='Text_news'),
    path('news/create/', CreateNews.as_view(), name='News_create'),
    path('news/<int:pk>/edit/', UpdateNews.as_view(), name='News_update'),
    path('news/<int:pk>/delete/', DeleteNews.as_view(), name='News_delete'),
    path('articles/create/', ArticlesCreate.as_view(), name='Articles_create'),
    path('articles/<int:pk>/edit', UpdateArticles.as_view(), name='Articles_update'),
    path('articles/<int:pk>/delete', DeleteArticles.as_view(), name='Articles_delete'),
    path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
    path('categories/<int:pk>/unsubscribe', unsubscribe, name='unsubscribe'),
]

newspaper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('accounts/', include('allauth.urls')),
    path('news/', include('news.urls')),

]

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.core.cache import cache

class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        postRat = self.post_set.aggregate(postRating=Sum('rating'))
        pRat = 0
        pRat += postRat.get('postRating')

        commentRat = self.authorUser.comment_set.aggregate(commentRating=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commentRating')

        self.ratingAuthor = pRat * 3 + cRat
        self.save()

class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES = [
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья')
    ]
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through='PostCategory')
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

    def get_absolute_url(self):
        return reverse('Text_news', args=[str(self.id)])

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete(f'post-{self.pk}')


class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    commentTime = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

templates/categorylist.html
{% extends 'flatpages/default.html'%}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}
    {% if is_not_subscriber %}
        <p class="text-center"><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться</a></p>
    {% endif %}
    {% if is_subscriber %}
        <p class="text-center"><a href="{% url 'unsubscribe' category.id %}" class="btn btn-secondary btn-sm">Отписаться</a></p>
    {% endif %}
    <hr>

    {% if category_news_list %}
    <table>
        <tr>
            <td><h1>НОВОСТИ</h1></td>
            <td><h1><p style="text-indent:1060px">{{category_news_list|length}}</p></h1></td>
        </tr>
    </table>
    <hr>
    <table>
        <tr>
            <td><h1>Заголовок</h1></td>
            <td><h1>Предосмотр</h1></td>
            <td><h1>Категории</h1></td>
            <td><h1>Дата</h1></td>
            {% if perms.news.change_post or perms.news.delete_post %}
            <td>Действия</td>
            {% endif %}
        </tr>

        {% for news in category_news_list %}
        <tr>
            <td><h3><a href="{% url 'Text_news' pk=news.id %} ">{{ news.title|censor }}</a></h3></td>
            <td><h3>{{ news.text|truncatechars:20|censor }}</h3></td>
            <td>
            {% for category in news.postCategory.all %}
                <a href="{% url 'category_list' category.id %}">{{ category.name }}</a>
            {% endfor %}
            </td>
            <td><h3>{{ news.dateCreation|date:'d m Y' }}</h3></td>

            <td>
                {% if perms.news.change_post %}
                <a href="{% url 'News_update' pk=news.id %}">Изменить</a>
                {% endif %}
                {% if perms.news.delete_post %}
                <a href="{% url 'News_delete' news.id %}">Удалить</a>
                {% endif %}
            </td>

        </tr>
        {% endfor %}
    </table>

    {% else %}
        <h2>Новостей нет</h2>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

templates/dayly_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h2>Добрый вечер! Вот новые статьи за последнюю неделю</h2>
<ul>
    {% for post in posts %}
        <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a> </li>
    {% endfor %}
</ul>
</body>
</html>

templates/mainnews.html
{% extends 'flatpages/default.html'%}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
News
{% endblock title %}

{% block content %}

    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>

    <hr>

    {% if perms.news.add_post %}
    <a href="{% url 'News_create' %}">Добавить Новость</a>
    <a href="{% url 'Articles_create' %}">Добавить Статью</a>
    {% endif %}


    {% if posts %}
    <table>
        <tr>
            <td><h1>НОВОСТИ</h1></td>
            <td><h1><p style="text-indent:1060px">{{posts|length}}</p></h1></td>
        </tr>
    </table>
    <hr>
    <table>
        <tr>
            <td><h1>Заголовок</h1></td>
            <td><h1>Предосмотр</h1></td>
            <td><h1>Категории</h1></td>
            <td><h1>Дата</h1></td>
            {% if perms.news.change_post or perms.news.delete_post %}
            <td>Действия</td>
            {% endif %}
        </tr>

        {% for news in posts %}
        <tr>
            <td><h3><a href="{% url 'Text_news' pk=news.id %} ">{{ news.title|censor }}</a></h3></td>
            <td><h3>{{ news.text|truncatechars:20|censor }}</h3></td>
            <td>
            {% for category in news.postCategory.all %}
                <a href="{% url 'category_list' category.id %}">{{ category.name }}</a>
            {% endfor %}
            </td>
            <td><h3>{{ news.dateCreation|date:'d m Y' }}</h3></td>

            <td>
                {% if perms.news.change_post %}
                <a href="{% url 'News_update' pk=news.id %}">Изменить</a>
                {% endif %}
                {% if perms.news.delete_post %}
                <a href="{% url 'News_delete' news.id %}">Удалить</a>
                {% endif %}
            </td>

        </tr>
        {% endfor %}
    </table>

    {% else %}
        <h2>Новостей нет</h2>
    {% endif %}

    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=1 %}">1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {% endif %}
    {% endif %}

    {{ page_obj.number }}

    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

templates/news_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление Статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ post.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

templates/news_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создание и Редактирование </h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуйте! Новая <a href="{{ link }}">статья</a> в твоем любимом разделе!</h2>
<p>{{ text }}</p>
</body>
</html>

templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
  <h1 class="text-center">{{ message }} на {{ category }}</h1>
{% endblock content%}

templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Подписки
{% endblock title %}

{% block content %}
    {% for category in categories %}
        <p>
            {{category.name}}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}

templates/textnews.html
{% extends 'flatpages/default.html'%}
{% load custom_filters %}
{% load custom_tags %}

{% block title %}
{{ post.title }}
{% endblock title %}

{% block content %}
<h1>{{ post.title|censor }}</h1>
<h1>{{ post.dateCreation|date:'d m Y' }} </h1>
<hr>
<h3>{{ post.text|censor }}</h3>
{% endblock content %}

templates/unsubscribe.html
{% extends 'flatpages/default.html' %}

{% block content %}
  <h1 class="text-center">{{ message }} от {{ category }}</h1>
{% endblock content %}